### ISSUE TITLE
Wagenreihung / Train information sometimes does not show up in train detail view

### ISSUE THREAD

**Issue by TomasKostadinov** [marudor/BahnhofsAbfahrten#282] opened 2020-03-13 10:29 UTC
**Describe the bug**
Sometimes there is no information on the train type and order ("Wagenreihung") in the train detail view although it exists.

**To Reproduce**
1. Search for a train
2. Click on the train and go to the route and timetable view
3. There is no information about the train type and order displayed

**Expected behavior**
I should be able to see the train oder and type ("Wagenreihung") if there is information about it.
I know that Wagenreihung information exists for this train because it can be seen in the train station view 

**Screenshots**

Train station view

![Bildschirmfoto 2020-03-13 um 11 11 57](https://user-images.githubusercontent.com/11008743/76612755-3bcd7900-651d-11ea-9fdd-bec8147e27c2.png)

Train detail view of same train

![Bildschirmfoto 2020-03-13 um 11 13 24](https://user-images.githubusercontent.com/11008743/76612788-4851d180-651d-11ea-9742-52a929317c68.png)

**Additional context**

This might be caused by the fact that this particular train is beeing used in a double ICE configuration.

Also an general suggestion: Let users click on stops in the train detail view and show the Wagenreihung for the clicked train station, not only the next one.

Thank you for your work and this amazing plattform! I really like using it!

**Comment by marudor** [comment] 2020-04-24 07:53
Bug:
Sadly not a bug on my site.S Problem ist that in trains that consist of 2 parts sometimes only one of the numbers has a couch sequence in the API. But with both train parts.
For the normal departure interface I fallback to try the other number if the original does not have any sequence.
Sadly I do not know hte other part in the details page => I can't check the other number.
So I can't really fix it as it's a problem of the bahn API.
Will check if I somehow can find the second number on the details page - that would fix it.

For the feature request: On the roadmap for quite a while now.

**Comment by TomasKostadinov** [comment] 2020-04-24 08:12
Thank you for your update on this bug, I already thought that this is a problem introduced by the api.
That would be cool if you could find a workaround.

Thumbs up for your work! 👍🏽

**Comment by marudor** [comment] 2021-01-05 09:23
No workaround possible. Closed as I can't fix it - it will be fixed if I get better information.

**Closed by marudor** 2021-01-05 09:23 UTC
Labels: bug
